from sqlalchemy.orm import Session

from app.models import Computer


SEED_COMPUTERS = [
    {
        "name": "Office Basic A1",
        "description": "Quiet office PC for documents, browser, and video calls.",
        "price": 499.0,
        "cpu": "Intel Core i3-12100",
        "gpu": None,
        "ram_gb": 8,
        "ssd_gb": 256,
        "has_windows": True,
        "image_url": "https://placehold.co/640x360/png?text=Office+A1",
        "shop_name": "PC Mart",
        "shop_url": "https://example.com/office-a1",
        "category_code": "office",
        "is_active": True,
    },
    {
        "name": "Office Plus A2",
        "description": "Office desktop with extra RAM for multitasking.",
        "price": 649.0,
        "cpu": "AMD Ryzen 5 5600G",
        "gpu": None,
        "ram_gb": 16,
        "ssd_gb": 512,
        "has_windows": True,
        "image_url": "https://placehold.co/640x360/png?text=Office+A2",
        "shop_name": "PC Mart",
        "shop_url": "https://example.com/office-a2",
        "category_code": "office",
        "is_active": True,
    },
    {
        "name": "Campus Start S1",
        "description": "Student-friendly PC for online classes and reports.",
        "price": 579.0,
        "cpu": "Intel Core i5-12400",
        "gpu": None,
        "ram_gb": 16,
        "ssd_gb": 512,
        "has_windows": True,
        "image_url": "https://placehold.co/640x360/png?text=Study+S1",
        "shop_name": "EduTech",
        "shop_url": "https://example.com/study-s1",
        "category_code": "study",
        "is_active": True,
    },
    {
        "name": "CodeBox Dev P1",
        "description": "Programming PC for Docker, backend, and IDE workflows.",
        "price": 949.0,
        "cpu": "AMD Ryzen 7 5700X",
        "gpu": "NVIDIA GTX 1660",
        "ram_gb": 32,
        "ssd_gb": 1000,
        "has_windows": True,
        "image_url": "https://placehold.co/640x360/png?text=Programming+P1",
        "shop_name": "Dev Computers",
        "shop_url": "https://example.com/programming-p1",
        "category_code": "programming",
        "is_active": True,
    },
    {
        "name": "CodeBox Dev P2",
        "description": "Balanced machine for coding, local databases, and containers.",
        "price": 1129.0,
        "cpu": "Intel Core i7-13700",
        "gpu": "NVIDIA RTX 4060",
        "ram_gb": 32,
        "ssd_gb": 1000,
        "has_windows": True,
        "image_url": "https://placehold.co/640x360/png?text=Programming+P2",
        "shop_name": "Dev Computers",
        "shop_url": "https://example.com/programming-p2",
        "category_code": "programming",
        "is_active": True,
    },
    {
        "name": "GameRush G1",
        "description": "Entry gaming PC for esports titles like CS2 and Dota 2.",
        "price": 1099.0,
        "cpu": "AMD Ryzen 5 7600",
        "gpu": "NVIDIA RTX 4060",
        "ram_gb": 16,
        "ssd_gb": 1000,
        "has_windows": True,
        "image_url": "https://placehold.co/640x360/png?text=Gaming+G1",
        "shop_name": "GameHub",
        "shop_url": "https://example.com/gaming-g1",
        "category_code": "gaming",
        "is_active": True,
    },
    {
        "name": "GameRush G2",
        "description": "High-FPS gaming build for modern AAA games.",
        "price": 1499.0,
        "cpu": "Intel Core i7-14700F",
        "gpu": "NVIDIA RTX 4070",
        "ram_gb": 32,
        "ssd_gb": 1000,
        "has_windows": True,
        "image_url": "https://placehold.co/640x360/png?text=Gaming+G2",
        "shop_name": "GameHub",
        "shop_url": "https://example.com/gaming-g2",
        "category_code": "gaming",
        "is_active": True,
    },
    {
        "name": "StudioCut V1",
        "description": "Video editing workstation for Premiere Pro and DaVinci Resolve.",
        "price": 1699.0,
        "cpu": "AMD Ryzen 9 7900",
        "gpu": "NVIDIA RTX 4070 Super",
        "ram_gb": 32,
        "ssd_gb": 2000,
        "has_windows": True,
        "image_url": "https://placehold.co/640x360/png?text=Video+V1",
        "shop_name": "Creator Store",
        "shop_url": "https://example.com/video-v1",
        "category_code": "video_editing",
        "is_active": True,
    },
    {
        "name": "RenderMax D1",
        "description": "3D workstation for Blender, CAD, and rendering scenes.",
        "price": 1999.0,
        "cpu": "Intel Core i9-14900KF",
        "gpu": "NVIDIA RTX 4070 Ti",
        "ram_gb": 64,
        "ssd_gb": 2000,
        "has_windows": True,
        "image_url": "https://placehold.co/640x360/png?text=3D+D1",
        "shop_name": "Creator Store",
        "shop_url": "https://example.com/design-d1",
        "category_code": "design_3d",
        "is_active": True,
    },
    {
        "name": "RenderMax D2",
        "description": "Advanced 3D and simulation machine for heavy projects.",
        "price": 2499.0,
        "cpu": "AMD Ryzen 9 7950X",
        "gpu": "NVIDIA RTX 4080",
        "ram_gb": 64,
        "ssd_gb": 2000,
        "has_windows": True,
        "image_url": "https://placehold.co/640x360/png?text=3D+D2",
        "shop_name": "Creator Store",
        "shop_url": "https://example.com/design-d2",
        "category_code": "design_3d",
        "is_active": False,
    },
]


def seed_data(db: Session):
    exists = db.query(Computer).first()
    if exists:
        return

    for item in SEED_COMPUTERS:
        db.add(Computer(**item))

    db.commit()
